import * as Knex from 'knex'

import * as movie from '../movie'

const sampleMovies = [
    { id: 601, original_title: 'E.T. the Extra-Terrestrial', adult: false, video: true, popularity: 1 },
    { id: 602, original_title: 'Independence Day', adult: false, video: true, popularity: 1 },
    { id: 603, original_title: 'The Matrix', adult: false, video: true, popularity: 1 },
    { id: 604, original_title: 'The Matrix Reloaded', adult: false, video: true, popularity: 1 },
    { id: 605, original_title: 'The Matrix Revolutions', adult: false, video: true, popularity: 1 },
    { id: 606, original_title: 'Out of Africa', adult: false, video: true, popularity: 1 },
    { id: 607, original_title: 'Men in Black', adult: false, video: true, popularity: 1 },
    { id: 608, original_title: 'Men in Black II', adult: false, video: true, popularity: 1 },
    { id: 609, original_title: 'Poltergeist', adult: false, video: true, popularity: 1 },
    { id: 612, original_title: 'Munich', adult: false, video: true, popularity: 1 },
    { id: 613, original_title: 'Der Untergang', adult: false, video: true, popularity: 1 },
    { id: 614, original_title: 'Smultronstället', adult: false, video: true, popularity: 1 },
    { id: 615, original_title: 'The Passion of the Christ', adult: false, video: true, popularity: 1 },
    { id: 616, original_title: 'The Last Samurai', adult: false, video: true, popularity: 1 },
    { id: 617, original_title: 'Wild Things', adult: false, video: true, popularity: 1 },
    { id: 618, original_title: 'The Birth of a Nation', adult: false, video: true, popularity: 1 },
    { id: 619, original_title: 'The Bodyguard', adult: false, video: true, popularity: 1 },
    { id: 620, original_title: 'Ghostbusters', adult: false, video: true, popularity: 1 },
    { id: 621, original_title: 'Grease', adult: false, video: true, popularity: 1 },
    { id: 622, original_title: 'The Ninth Gate', adult: false, video: true, popularity: 1 },
    { id: 623, original_title: 'A Fish Called Wanda', adult: false, video: true, popularity: 1 },
    { id: 624, original_title: 'Easy Rider', adult: false, video: true, popularity: 1 },
    { id: 625, original_title: 'The Killing Fields', adult: false, video: true, popularity: 1 },
    { id: 626, original_title: 'Un chien andalou', adult: false, video: true, popularity: 1 },
    { id: 627, original_title: 'Trainspotting', adult: false, video: true, popularity: 1 },
    { id: 628, original_title: 'Interview with the Vampire', adult: false, video: true, popularity: 1 },
    { id: 629, original_title: 'The Usual Suspects', adult: false, video: true, popularity: 1 },
    { id: 630, original_title: 'The Wizard of Oz', adult: false, video: true, popularity: 1 },
    { id: 631, original_title: 'Sunrise: A Song of Two Humans', adult: false, video: true, popularity: 1 },
    { id: 632, original_title: 'Stalag 17', adult: false, video: true, popularity: 1 },
    { id: 633, original_title: 'Soldaat van Oranje', adult: false, video: true, popularity: 1 },
    { id: 634, original_title: "Bridget Jones's Diary", adult: false, video: true, popularity: 1 },
    { id: 635, original_title: 'Angel Heart', adult: false, video: true, popularity: 1 },
    { id: 636, original_title: 'THX 1138', adult: false, video: true, popularity: 1 },
    { id: 637, original_title: 'La vita è bella', adult: false, video: true, popularity: 1 },
    { id: 638, original_title: 'Lost Highway', adult: false, video: true, popularity: 1 },
    { id: 639, original_title: 'When Harry Met Sally', adult: false, video: true, popularity: 1 },
    { id: 640, original_title: 'Catch Me If You Can', adult: false, video: true, popularity: 1 },
    { id: 641, original_title: 'Requiem for a Dream', adult: false, video: true, popularity: 1 },
    { id: 642, original_title: 'Butch Cassidy and the Sundance Kid', adult: false, video: true, popularity: 1 },
    { id: 643, original_title: 'Броненосец Потёмкин', adult: false, video: true, popularity: 1 },
    { id: 644, original_title: 'A.I. Artificial Intelligence', adult: false, video: true, popularity: 1 },
    { id: 646, original_title: 'Dr. No', adult: false, video: true, popularity: 1 },
    { id: 647, original_title: 'Final Fantasy VII: Advent Children', adult: false, video: true, popularity: 1 },
    { id: 648, original_title: 'La belle et la bête', adult: false, video: true, popularity: 1 },
    { id: 649, original_title: 'Belle de jour', adult: false, video: true, popularity: 1 },
    { id: 650, original_title: 'Boyz n the Hood', adult: false, video: true, popularity: 1 },
    { id: 651, original_title: 'M*A*S*H', adult: false, video: true, popularity: 1 },
    { id: 652, original_title: 'Troy', adult: false, video: true, popularity: 1 },
    { id: 653, original_title: 'Nosferatu, eine Symphonie des Grauens', adult: false, video: true, popularity: 1 },
    { id: 654, original_title: 'On the Waterfront', adult: false, video: true, popularity: 1 },
    { id: 655, original_title: 'Paris, Texas', adult: false, video: true, popularity: 1 },
    { id: 657, original_title: 'From Russia with Love', adult: false, video: true, popularity: 1 },
    { id: 658, original_title: 'Goldfinger', adult: false, video: true, popularity: 1 },
    { id: 659, original_title: 'Die Blechtrommel', adult: false, video: true, popularity: 1 },
    { id: 660, original_title: 'Thunderball', adult: false, video: true, popularity: 1 },
    { id: 661, original_title: 'Die Ehe der Maria Braun', adult: false, video: true, popularity: 1 },
    { id: 662, original_title: 'La Jetée', adult: false, video: true, popularity: 1 },
    { id: 663, original_title: 'Saw IV', adult: false, video: true, popularity: 1 },
    { id: 664, original_title: 'Twister', adult: false, video: true, popularity: 1 },
    { id: 665, original_title: 'Ben-Hur', adult: false, video: true, popularity: 1 },
    { id: 666, original_title: 'Central do Brasil', adult: false, video: true, popularity: 1 },
    { id: 667, original_title: 'You Only Live Twice', adult: false, video: true, popularity: 1 },
    { id: 668, original_title: "On Her Majesty's Secret Service", adult: false, video: true, popularity: 1 },
    { id: 669, original_title: 'Nanook of the North', adult: false, video: true, popularity: 1 },
    { id: 670, original_title: '올드보이', adult: false, video: true, popularity: 1 },
    { id: 671, original_title: "Harry Potter and the Philosopher's Stone", adult: false, video: true, popularity: 1 },
    { id: 672, original_title: 'Harry Potter and the Chamber of Secrets', adult: false, video: true, popularity: 1 },
    { id: 673, original_title: 'Harry Potter and the Prisoner of Azkaban', adult: false, video: true, popularity: 1 },
    { id: 674, original_title: 'Harry Potter and the Goblet of Fire', adult: false, video: true, popularity: 1 },
    { id: 675, original_title: 'Harry Potter and the Order of the Phoenix', adult: false, video: true, popularity: 1 },
    { id: 676, original_title: 'Pearl Harbor', adult: false, video: true, popularity: 1 },
    { id: 677, original_title: 'Olympia - Fest der Völker', adult: false, video: true, popularity: 1 },
    { id: 678, original_title: 'Out of the Past', adult: false, video: true, popularity: 1 },
    { id: 679, original_title: 'Aliens', adult: false, video: true, popularity: 1 },
    { id: 680, original_title: 'Pulp Fiction', adult: false, video: true, popularity: 1 },
    { id: 681, original_title: 'Diamonds Are Forever', adult: false, video: true, popularity: 1 },
    { id: 682, original_title: 'The Man with the Golden Gun', adult: false, video: true, popularity: 1 },
    { id: 685, original_title: 'Olympia - Fest der Schönheit', adult: false, video: true, popularity: 1 },
    { id: 686, original_title: 'Contact', adult: false, video: true, popularity: 1 },
    { id: 687, original_title: 'Dead Man Walking', adult: false, video: true, popularity: 1 },
    { id: 688, original_title: 'The Bridges of Madison County', adult: false, video: true, popularity: 1 },
    { id: 689, original_title: 'Ο θίασος', adult: false, video: true, popularity: 1 },
    { id: 690, original_title: 'Pickpocket', adult: false, video: true, popularity: 1 },
    { id: 691, original_title: 'The Spy Who Loved Me', adult: false, video: true, popularity: 1 },
    { id: 692, original_title: 'Pink Flamingos', adult: false, video: true, popularity: 1 },
    { id: 693, original_title: 'Meet the Fockers', adult: false, video: true, popularity: 1 },
    { id: 694, original_title: 'The Shining', adult: false, video: true, popularity: 1 },
    { id: 695, original_title: 'Short Cuts', adult: false, video: true, popularity: 1 },
    { id: 696, original_title: 'Manhattan', adult: false, video: true, popularity: 1 },
    { id: 697, original_title: 'Oktyabr', adult: false, video: true, popularity: 1 },
    { id: 698, original_title: 'Moonraker', adult: false, video: true, popularity: 1 },
    { id: 699, original_title: 'For Your Eyes Only', adult: false, video: true, popularity: 1 },
    { id: 700, original_title: 'Octopussy', adult: false, video: true, popularity: 1 },
    { id: 701, original_title: 'Our Hospitality', adult: false, video: true, popularity: 1 },
    { id: 702, original_title: 'A Streetcar Named Desire', adult: false, video: true, popularity: 1 },
    { id: 703, original_title: 'Annie Hall', adult: false, video: true, popularity: 1 },
    { id: 704, original_title: "A Hard Day's Night", adult: false, video: true, popularity: 1 },
    { id: 705, original_title: 'All About Eve', adult: false, video: true, popularity: 1 },
    { id: 706, original_title: 'Fontane Effi Briest', adult: false, video: true, popularity: 1 }
]

exports.seed = (knex: Knex) => {
    return knex('movies')
        .del()
        .then(() => {
            return knex('movies').insert(sampleMovies)
        })
}
